version: '3.1'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./service/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - service

    service:
        build: service
        ports:
            - 8080:8080
