version: '3.1'
services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80

    get_service:
        build: .
        ports:
        - "8080:8080"
        volumes:
        - .:/service
